# Generated by Django 4.2 on 2026-06-30

from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='property_photos/',
                validators=[FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])],
            ),
        ),
    ]
